height_m: 1.8
in_radius_m: 0.172
foot_length_m: 0.27
foot_width_m: 0.09
nominal_offset_m: 0.16
num_theta_vals: 32
goal_tolerance_m: 0.2
collision_spheres {
  x: 0.00516
  y: 0.10536
  z: 0.05408
  radius: 0.056
  origin: RIGHT_FOOT
}
collision_spheres {
  x: 0.00939
  y: 0.03095
  z: 0.06195
  radius: 0.061
  origin: RIGHT_FOOT
}
collision_spheres {
  x: -0.00495
  y: -0.05972
  z: 0.08263
  radius: 0.08
  origin: RIGHT_FOOT
}
collision_spheres {
  x: 0.00018
  y: -0.03331
  z: 0.46149
  radius: 0.18174
  origin: RIGHT_FOOT
}
collision_spheres {
  x: -0.00516
  y: 0.10536
  z: 0.05408
  radius: 0.056
  origin: LEFT_FOOT
}
collision_spheres {
  x: -0.00939
  y: 0.03095
  z: 0.06195
  radius: 0.061
  origin: LEFT_FOOT
}
collision_spheres {
  x: 0.00495
  y: -0.05972
  z: 0.08263
  radius: 0.08
  origin: LEFT_FOOT
}
collision_spheres {
  x: -0.00018
  y: -0.03331
  z: 0.46149
  radius: 0.18174
  origin: LEFT_FOOT
}
collision_spheres {
  x: 0.0
  y: 0.0
  z: 1.50045
  radius: 0.31532
  origin: FEET_CENTER
}
collision_spheres {
  x: 0.16634
  y: 0.0
  z: 0.85813
  radius: 0.089
  origin: FEET_CENTER
}
collision_spheres {
  x: 0.0
  y: 0.0
  z: 0.85813
  radius: 0.091
  origin: FEET_CENTER
}
collision_spheres {
  x: 0.20552
  y: 0.09658
  z: 0.95356
  radius: 0.065
  origin: FEET_CENTER
}
collision_spheres {
  x: 0.0
  y: -0.05719
  z: 1.04311
  radius: 0.084
  origin: FEET_CENTER
}
collision_spheres {
  x: 0.0
  y: 0.06194
  z: 1.060307
  radius: 0.084
  origin: FEET_CENTER
}
collision_spheres {
  x: 0.19463
  y: 0.03235
  z: 1.32774
  radius: 0.091
  origin: FEET_CENTER
}
collision_spheres {
  x: -0.16634
  y: 0.0
  z: 0.85813
  radius: 0.089
  origin: FEET_CENTER
}
collision_spheres {
  x: -0.20552
  y: 0.09658
  z: 0.95356
  radius: 0.065
  origin: FEET_CENTER
}
collision_spheres {
  x: -0.19463
  y: 0.03235
  z: 1.32774
  radius: 0.091
  origin: FEET_CENTER
}
motion_primitives {
  dx: 1
  dy: 1
  dz: 0
}
motion_primitives {
  dx: 0.9
  dy: 0.9
  dz: 0
} 
motion_primitives {
  dx: 0.8
  dy: 0.8
  dz: 0
}
motion_primitives {
  dx: 0.7
  dy: 0.7
  dz: 0
}
motion_primitives {
  dx: 0.6
  dy: 0.6
  dz: 0
}
motion_primitives {
  dx: 0.5
  dy: 0.5
  dz: 0
} 
motion_primitives {
  dx: 0.4
  dy: 0.4
  dz: 0
} 
motion_primitives {
  dx: 0.3
  dy: 0.3
  dz: 0
} 
motion_primitives {
  dx: 0.2
  dy: 0.2
  dz: 0
}
motion_primitives {
  dx: 0.1
  dy: 0.1
  dz: 0
}
motion_primitives {
  dx: 0
  dy: 0
  dz: 0
}
motion_primitives {
  dx: 1
  dy: 1
  dz: 1
}
motion_primitives {
  dx: 1
  dy: 0
  dz: 1
}
motion_primitives {
  dx: 0
  dy: 1
  dz: 1
}
motion_primitives {
  dx: 2
  dy: 2
  dz: 1
}
motion_primitives {
  dx: 0
  dy: 2
  dz: 1
}
motion_primitives {
  dx: 2
  dy: 0
  dz: 1
}
motion_primitives {
  dx: 1
  dy: 1
  dz: 2
}
motion_primitives {
  dx: 0
  dy: 1
  dz: 2
}
motion_primitives {
  dx: 1
  dy: 0
  dz: 2
}
motion_primitives {
  dx: 2
  dy: 2
  dz: 2
}
motion_primitives {
  dx: 0
  dy: 2
  dz: 2
}
motion_primitives {
  dx: 2
  dy: 0
  dz: 2
}
motion_primitives {
  dx: 1
  dy: 1
  dz: 3
}
motion_primitives {
  dx: 0
  dy: 1
  dz: 3
}
motion_primitives {
  dx: 1
  dy: 0
  dz: 3
}
motion_primitives {
  dx: 1
  dy: 1
  dz: -1
}
motion_primitives {
  dx: 1
  dy: 0
  dz: -1
}
motion_primitives {
  dx: 0
  dy: 1
  dz: -1
}
motion_primitives {
  dx: 2
  dy: 2
  dz: -1
}
motion_primitives {
  dx: 0
  dy: 2
  dz: -1
}
motion_primitives {
  dx: 2
  dy: 0
  dz: -1
}
motion_primitives {
  dx: 1
  dy: 1
  dz: -2
}
motion_primitives {
  dx: 0
  dy: 1
  dz: -2
}
motion_primitives {
  dx: 1
  dy: 0
  dz: -2
}
motion_primitives {
  dx: 2
  dy: 2
  dz: -2
}
motion_primitives {
  dx: 0
  dy: 2
  dz: -2
}
motion_primitives {
  dx: 2
  dy: 0
  dz: -2
}
motion_primitives {
  dx: 1
  dy: 1
  dz: -3
}
motion_primitives {
  dx: 0
  dy: 1
  dz: -3
}
motion_primitives {
  dx: 1
  dy: 0
  dz: -3
}
