# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: homotopy_information.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import environment_projections_pb2 as environment__projections__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='homotopy_information.proto',
  package='footstep_planner.graphs.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x1ahomotopy_information.proto\x12\x1d\x66ootstep_planner.graphs.proto\x1a\x1d\x65nvironment_projections.proto\"\x82\x01\n\x05\x42\x65\x61ms\x12\x38\n\x05\x62\x65\x61ms\x18\x01 \x03(\x0b\x32).footstep_planner.graphs.proto.Beams.Beam\x1a?\n\x04\x42\x65\x61m\x12\t\n\x01x\x18\x01 \x02(\r\x12\t\n\x01y\x18\x02 \x02(\r\x12\x11\n\tworkspace\x18\x03 \x02(\r\x12\x0e\n\x06letter\x18\x04 \x02(\r\"\xa3\x01\n\x05Gates\x12\x38\n\x05gates\x18\x01 \x03(\x0b\x32).footstep_planner.graphs.proto.Gates.Gate\x1a`\n\x04Gate\x12H\n\nworkspaces\x18\x01 \x02(\x0b\x32\x34.footstep_planner.environment.proto.WorkspaceIndices\x12\x0e\n\x06letter\x18\x02 \x02(\r')
  ,
  dependencies=[environment__projections__pb2.DESCRIPTOR,])




_BEAMS_BEAM = _descriptor.Descriptor(
  name='Beam',
  full_name='footstep_planner.graphs.proto.Beams.Beam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='footstep_planner.graphs.proto.Beams.Beam.x', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='footstep_planner.graphs.proto.Beams.Beam.y', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workspace', full_name='footstep_planner.graphs.proto.Beams.Beam.workspace', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='letter', full_name='footstep_planner.graphs.proto.Beams.Beam.letter', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=223,
)

_BEAMS = _descriptor.Descriptor(
  name='Beams',
  full_name='footstep_planner.graphs.proto.Beams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='beams', full_name='footstep_planner.graphs.proto.Beams.beams', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BEAMS_BEAM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=223,
)


_GATES_GATE = _descriptor.Descriptor(
  name='Gate',
  full_name='footstep_planner.graphs.proto.Gates.Gate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='workspaces', full_name='footstep_planner.graphs.proto.Gates.Gate.workspaces', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='letter', full_name='footstep_planner.graphs.proto.Gates.Gate.letter', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=389,
)

_GATES = _descriptor.Descriptor(
  name='Gates',
  full_name='footstep_planner.graphs.proto.Gates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gates', full_name='footstep_planner.graphs.proto.Gates.gates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GATES_GATE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=389,
)

_BEAMS_BEAM.containing_type = _BEAMS
_BEAMS.fields_by_name['beams'].message_type = _BEAMS_BEAM
_GATES_GATE.fields_by_name['workspaces'].message_type = environment__projections__pb2._WORKSPACEINDICES
_GATES_GATE.containing_type = _GATES
_GATES.fields_by_name['gates'].message_type = _GATES_GATE
DESCRIPTOR.message_types_by_name['Beams'] = _BEAMS
DESCRIPTOR.message_types_by_name['Gates'] = _GATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Beams = _reflection.GeneratedProtocolMessageType('Beams', (_message.Message,), dict(

  Beam = _reflection.GeneratedProtocolMessageType('Beam', (_message.Message,), dict(
    DESCRIPTOR = _BEAMS_BEAM,
    __module__ = 'homotopy_information_pb2'
    # @@protoc_insertion_point(class_scope:footstep_planner.graphs.proto.Beams.Beam)
    ))
  ,
  DESCRIPTOR = _BEAMS,
  __module__ = 'homotopy_information_pb2'
  # @@protoc_insertion_point(class_scope:footstep_planner.graphs.proto.Beams)
  ))
_sym_db.RegisterMessage(Beams)
_sym_db.RegisterMessage(Beams.Beam)

Gates = _reflection.GeneratedProtocolMessageType('Gates', (_message.Message,), dict(

  Gate = _reflection.GeneratedProtocolMessageType('Gate', (_message.Message,), dict(
    DESCRIPTOR = _GATES_GATE,
    __module__ = 'homotopy_information_pb2'
    # @@protoc_insertion_point(class_scope:footstep_planner.graphs.proto.Gates.Gate)
    ))
  ,
  DESCRIPTOR = _GATES,
  __module__ = 'homotopy_information_pb2'
  # @@protoc_insertion_point(class_scope:footstep_planner.graphs.proto.Gates)
  ))
_sym_db.RegisterMessage(Gates)
_sym_db.RegisterMessage(Gates.Gate)


# @@protoc_insertion_point(module_scope)
