# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_parameters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot_parameters.proto',
  package='footstep_planner.proto',
  syntax='proto2',
  serialized_pb=_b('\n\x16robot_parameters.proto\x12\x16\x66ootstep_planner.proto\"\xcb\x01\n\x10\x43ollisionSpheres\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\t\n\x01z\x18\x03 \x02(\x01\x12\x0e\n\x06radius\x18\x04 \x02(\x01\x12L\n\x06origin\x18\x05 \x02(\x0e\x32/.footstep_planner.proto.CollisionSpheres.Origin:\x0b\x46\x45\x45T_CENTER\"8\n\x06Origin\x12\r\n\tLEFT_FOOT\x10\x01\x12\x0e\n\nRIGHT_FOOT\x10\x02\x12\x0f\n\x0b\x46\x45\x45T_CENTER\x10\x03\"6\n\x10MotionPrimitives\x12\n\n\x02\x64x\x18\x01 \x02(\x01\x12\n\n\x02\x64y\x18\x02 \x02(\x01\x12\n\n\x02\x64z\x18\x03 \x02(\x01\"\xbb\x02\n\x0fRobotParameters\x12\x10\n\x08height_m\x18\x01 \x02(\x01\x12\x13\n\x0bin_radius_m\x18\x02 \x02(\x01\x12\x15\n\rfoot_length_m\x18\x03 \x02(\x01\x12\x14\n\x0c\x66oot_width_m\x18\x04 \x02(\x01\x12\x18\n\x10nominal_offset_m\x18\x05 \x02(\x01\x12\x16\n\x0enum_theta_vals\x18\x06 \x02(\r\x12\x18\n\x10goal_tolerance_m\x18\x07 \x02(\x01\x12\x43\n\x11\x63ollision_spheres\x18\x08 \x03(\x0b\x32(.footstep_planner.proto.CollisionSpheres\x12\x43\n\x11motion_primitives\x18\t \x03(\x0b\x32(.footstep_planner.proto.MotionPrimitives')
)



_COLLISIONSPHERES_ORIGIN = _descriptor.EnumDescriptor(
  name='Origin',
  full_name='footstep_planner.proto.CollisionSpheres.Origin',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEFT_FOOT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_FOOT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FEET_CENTER', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=198,
  serialized_end=254,
)
_sym_db.RegisterEnumDescriptor(_COLLISIONSPHERES_ORIGIN)


_COLLISIONSPHERES = _descriptor.Descriptor(
  name='CollisionSpheres',
  full_name='footstep_planner.proto.CollisionSpheres',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='footstep_planner.proto.CollisionSpheres.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='footstep_planner.proto.CollisionSpheres.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='footstep_planner.proto.CollisionSpheres.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius', full_name='footstep_planner.proto.CollisionSpheres.radius', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='origin', full_name='footstep_planner.proto.CollisionSpheres.origin', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COLLISIONSPHERES_ORIGIN,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=254,
)


_MOTIONPRIMITIVES = _descriptor.Descriptor(
  name='MotionPrimitives',
  full_name='footstep_planner.proto.MotionPrimitives',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dx', full_name='footstep_planner.proto.MotionPrimitives.dx', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dy', full_name='footstep_planner.proto.MotionPrimitives.dy', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dz', full_name='footstep_planner.proto.MotionPrimitives.dz', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=310,
)


_ROBOTPARAMETERS = _descriptor.Descriptor(
  name='RobotParameters',
  full_name='footstep_planner.proto.RobotParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height_m', full_name='footstep_planner.proto.RobotParameters.height_m', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='in_radius_m', full_name='footstep_planner.proto.RobotParameters.in_radius_m', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='foot_length_m', full_name='footstep_planner.proto.RobotParameters.foot_length_m', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='foot_width_m', full_name='footstep_planner.proto.RobotParameters.foot_width_m', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nominal_offset_m', full_name='footstep_planner.proto.RobotParameters.nominal_offset_m', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_theta_vals', full_name='footstep_planner.proto.RobotParameters.num_theta_vals', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='goal_tolerance_m', full_name='footstep_planner.proto.RobotParameters.goal_tolerance_m', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='collision_spheres', full_name='footstep_planner.proto.RobotParameters.collision_spheres', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='motion_primitives', full_name='footstep_planner.proto.RobotParameters.motion_primitives', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=628,
)

_COLLISIONSPHERES.fields_by_name['origin'].enum_type = _COLLISIONSPHERES_ORIGIN
_COLLISIONSPHERES_ORIGIN.containing_type = _COLLISIONSPHERES
_ROBOTPARAMETERS.fields_by_name['collision_spheres'].message_type = _COLLISIONSPHERES
_ROBOTPARAMETERS.fields_by_name['motion_primitives'].message_type = _MOTIONPRIMITIVES
DESCRIPTOR.message_types_by_name['CollisionSpheres'] = _COLLISIONSPHERES
DESCRIPTOR.message_types_by_name['MotionPrimitives'] = _MOTIONPRIMITIVES
DESCRIPTOR.message_types_by_name['RobotParameters'] = _ROBOTPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CollisionSpheres = _reflection.GeneratedProtocolMessageType('CollisionSpheres', (_message.Message,), dict(
  DESCRIPTOR = _COLLISIONSPHERES,
  __module__ = 'robot_parameters_pb2'
  # @@protoc_insertion_point(class_scope:footstep_planner.proto.CollisionSpheres)
  ))
_sym_db.RegisterMessage(CollisionSpheres)

MotionPrimitives = _reflection.GeneratedProtocolMessageType('MotionPrimitives', (_message.Message,), dict(
  DESCRIPTOR = _MOTIONPRIMITIVES,
  __module__ = 'robot_parameters_pb2'
  # @@protoc_insertion_point(class_scope:footstep_planner.proto.MotionPrimitives)
  ))
_sym_db.RegisterMessage(MotionPrimitives)

RobotParameters = _reflection.GeneratedProtocolMessageType('RobotParameters', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTPARAMETERS,
  __module__ = 'robot_parameters_pb2'
  # @@protoc_insertion_point(class_scope:footstep_planner.proto.RobotParameters)
  ))
_sym_db.RegisterMessage(RobotParameters)


# @@protoc_insertion_point(module_scope)
